#개발 DB
spring.profiles: win-dev
spring:
  
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
          ddl-auto: none
  datasource:
      url: jdbc:mysql://dev.c0gqj5ketijm.ap-northeast-2.rds.amazonaws.com:3306/lobig?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=utf-8&serverTimezone=UTC
      username: admin
      password: kncom1203!
      driver-class-name: com.mysql.cj.jdbc.Driver

---
#운영 DB
spring.profiles: real
spring:
  
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
          ddl-auto: none
  datasource:
      url: jdbc:mysql://nia.c0gqj5ketijm.ap-northeast-2.rds.amazonaws.com:3306/lobig?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: knc!Q@W#E
      driver-class-name: com.mysql.cj.jdbc.Driver
