#로컬 DB 연결 프로파일
pripertiyTest: test
spring.profiles: win-dev
spring:
  
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
          ddl-auto: none
  datasource:
      url: jdbc:mysql://dev.c0gqj5ketijm.ap-northeast-2.rds.amazonaws.com:3306/lobig?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=utf-8&serverTimezone=UTC
      username: admin
      password: kncom1203!
      driver-class-name: com.mysql.cj.jdbc.Driver

